# Generated by Django 4.2.6 on 2023-10-17 07:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='heritage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.FileField(max_length=250, null=None, upload_to='blog-img/')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
