# Generated by Django 4.2.6 on 2023-11-23 16:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsection', '0003_trending_remove_heritage_blog_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img1', models.FileField(max_length=250, null=None, upload_to='blog-img/')),
                ('blog_title1', models.CharField(max_length=100)),
                ('blog_desc1', tinymce.models.HTMLField()),
                ('blog_desc2', tinymce.models.HTMLField()),
                ('blog_title2', models.CharField(max_length=100)),
                ('blog_about', tinymce.models.HTMLField()),
                ('blog_img2', models.FileField(max_length=250, null=None, upload_to='blog-img/')),
            ],
        ),
    ]
