# Generated by Django 4.2.6 on 2023-11-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsection', '0004_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='blog_about',
            new_name='blog_desc3',
        ),
    ]
