# Generated by Django 4.2.6 on 2023-11-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsection', '0005_rename_blog_about_aboutus_blog_desc3'),
    ]

    operations = [
        migrations.CreateModel(
            name='allblogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_img', models.FileField(max_length=250, null=None, upload_to='blog-img/')),
                ('blog_title', models.CharField(max_length=100)),
            ],
        ),
    ]
