# Generated by Django 4.2.6 on 2023-11-26 11:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsection', '0006_allblogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogsdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title1', models.CharField(max_length=100)),
                ('blog_img1', models.FileField(max_length=250, null=None, upload_to='blog-img/')),
                ('blog_desc1', tinymce.models.HTMLField()),
                ('blog_img2', models.FileField(max_length=250, null=None, upload_to='blog-img/')),
                ('blog_desc2', tinymce.models.HTMLField()),
                ('blog_img3', models.FileField(max_length=250, null=None, upload_to='blog-img/')),
                ('blog_desc3', tinymce.models.HTMLField()),
            ],
        ),
    ]
