# Generated by Django 4.2.6 on 2023-11-29 10:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsection', '0007_blogsdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogsdetails',
        ),
        migrations.AddField(
            model_name='trending',
            name='blog_desc1',
            field=tinymce.models.HTMLField(default=404),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trending',
            name='blog_desc2',
            field=tinymce.models.HTMLField(default=404),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trending',
            name='blog_desc3',
            field=tinymce.models.HTMLField(default=404),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trending',
            name='blog_img2',
            field=models.FileField(default=404, max_length=250, null=None, upload_to='blog-img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trending',
            name='blog_img3',
            field=models.FileField(default=404, max_length=250, null=None, upload_to='blog-img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trending',
            name='blog_title1',
            field=models.CharField(default=404, max_length=100),
            preserve_default=False,
        ),
    ]
