# Generated by Django 4.2.6 on 2023-11-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsection', '0008_delete_blogsdetails_trending_blog_desc1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='heritage',
            new_name='latest',
        ),
        migrations.RenameModel(
            old_name='food',
            new_name='popular',
        ),
    ]
