# Generated by Django 4.2.6 on 2023-11-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsection', '0009_rename_heritage_latest_rename_food_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='blog_desc1',
            new_name='blog_desc',
        ),
        migrations.RenameField(
            model_name='trending',
            old_name='blog_title1',
            new_name='blog_title2',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='blog_desc2',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='blog_desc3',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='blog_img2',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='blog_img3',
        ),
    ]
