# Generated by Django 4.2.6 on 2023-11-30 07:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogsection', '0010_rename_blog_desc1_trending_blog_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='blog_desc',
            field=tinymce.models.HTMLField(default=404),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latest',
            name='blog_title2',
            field=models.CharField(default=404, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='blog_title2',
            field=models.CharField(default=404, max_length=100),
            preserve_default=False,
        ),
    ]
